CardsList = new Mongo.Collection('cards')
GamesList = new Mongo.Collection('games')
PromptsList = new Mongo.Collection('prompts')
GameUserRelsList = new Mongo.Collection('gameUserRels')
AlertsList = new Mongo.Collection('alerts')
JudgePilesList = new Mongo.Collection('judgePiles')